[features]
seeds = false
skip-lint = false

[programs.localnet]
anomi = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# --- CRITICAL CONFIGURATION ---
# OpenBook V2 integration temporarily disabled for core architecture testing
# Will be re-enabled once core flow is validated
# [[test.validator.clone]]
# address = "opnb2LAf4g9p7RG9T8a12gR5A9vG73E6T4vupS2b2b"
# path = "/home/zan_yder/serum-OpenBook-prototype/openbook-v2/target/deploy/openbook_v2.so"
