[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
market = "7eAHPRbhqzsqpC1Wuw2Y8AqRGGqGcEGAXAGmfsovfLae"

[programs.devnet]
market = "Bk2pKQsXXvjPChX2G8AWgwoefnwRbTSirtHGnG8yUEdB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
localnet = "anchor localnet"
