[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
market = "7eAHPRbhqzsqpC1Wuw2Y8AqRGGqGcEGAXAGmfsovfLae"
order_store = "CYgv14nE8urDSaLDw8uP5QJDpZP12mRgoX8nPMXuXM6P"
order_processor = "F1J8MS1XhZgALP4VSjrKHF4Kj3VaG1vnNUCtafVnHgKo"

[programs.devnet]
market = "EoDGhkuNrPXGciC1jE2VketUZn2hqqkh8jyrnwYs3h9H"
order_store = "DjuV2BhfeVSnamUNPQhjY1NxtCqDT8RjG8xyKJAN2spg"
order_processor = "6owJkVJUF6B4HeFXhHZcDPYFw4EyRbqvkT3mAns6Cdoq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
localnet = "anchor localnet"
